"""update database

Revision ID: da1e0684fc7d
Revises: 992639da1245
Create Date: 2024-09-08 14:56:57.015849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1e0684fc7d'
down_revision = '992639da1245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creators', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
